// Sealed credential storage.
//
// Stores named credentials in memory as AES-256-GCM
// ciphertext. Plaintext is never held in the store past the
// `unseal` call: callers receive a `Secret<String>` that
// zeroes its backing buffer on `Drop`.
//
// Threat model:
//   * The on-disk representation is never written here —
//     the in-memory store is process-local. A future
//     `aether-credential-journal` will add a tamper-evident
//     write-ahead log so credentials survive restarts
//     without ever touching plaintext on disk.
//   * The 32-byte sealing key never leaves the
//     `KeyProvider`. Callers cannot extract it.
//   * Each seal uses a fresh 96-bit nonce, generated by
//     `rand::thread_rng`.
//   * AES-256-GCM authenticates the ciphertext, so any
//     tampering with a stored blob is detected at
//     unseal-time.
//
// Wire format for `SealedBlob`:
//   * 12 bytes      : AES-GCM nonce
//   * N + 16 bytes  : ciphertext || GCM authentication tag
// Total length is therefore 28 + plaintext length.
//
// `aes-gcm`'s `encrypt` returns the ciphertext with the
// 16-byte tag already appended, so we store the buffer
// verbatim and split off the tag only when serialising.
//
// All secret material held in `Secret<T>` is wiped on drop
// via the `zeroize` crate. The non-secret metadata (the
// name, the timestamp, the blob bytes) is not wiped — those
// are not sensitive in isolation.

use aes_gcm::aead::array::Array;
use aes_gcm::aead::Aead;
use aes_gcm::{Aes256Gcm, KeyInit};
use rand::RngCore;
use serde::{Deserialize, Serialize};
use zeroize::{Zeroize, ZeroizeOnDrop};

/// A secret value that is wiped from memory on drop.
///
/// `Secret<T>` is the only way to extract plaintext from
/// the sealed store. The inner `T` is wiped on `Drop`,
/// even if the surrounding code panics.
#[derive(Debug, Clone, Zeroize, ZeroizeOnDrop)]
pub struct Secret<T: Zeroize>(T);

impl<T: Zeroize> Secret<T> {
    /// Wraps a value as a secret. The caller transfers
    /// ownership of the inner `T`.
    pub fn new(value: T) -> Self {
        Self(value)
    }

    /// Returns a reference to the inner value. The caller
    /// must not clone, log, or persist the borrowed data.
    pub fn expose(&self) -> &T {
        &self.0
    }
}

impl Secret<String> {
    /// Consumes the secret and returns the inner `String`.
    /// The caller is responsible for zeroing the returned
    /// value when done.
    pub fn into_inner(mut self) -> String {
        std::mem::take(&mut self.0)
    }
}

/// A sealed credential. The plaintext is recoverable only
/// by `SealedStore::unseal`, and only with the same key
/// that was used to seal it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SealedBlob {
    /// The wire-format bytes: nonce || ciphertext || tag.
    pub bytes: Vec<u8>,
    /// Optional human-readable label. Not authenticated
    /// by the AEAD — it is metadata, not part of the
    /// plaintext the seal protects.
    pub label: Option<String>,
    /// Unix epoch milliseconds when this blob was sealed.
    /// The store does not check it; callers can use it for
    /// rotation policy.
    pub sealed_at_ms: u64,
}

/// A credential record holds the name, the sealed blob,
/// and the original (unsealed) plaintext length so callers
/// can size buffers without unsealing first.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Credential {
    pub name: String,
    pub blob: SealedBlob,
    pub plaintext_len: usize,
}

/// Error from the sealed store.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CredentialError {
    /// The supplied name was not found in the store.
    NotFound,
    /// The blob failed AEAD authentication (wrong key or
    /// tampered ciphertext).
    AuthenticationFailed,
    /// The supplied name already exists. The store is
    /// upsert-by-default: pass `force = true` to overwrite.
    AlreadyExists { name: String },
    /// The blob's wire format is malformed (wrong length
    /// for nonce + tag).
    Malformed,
}

impl std::fmt::Display for CredentialError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotFound => f.write_str("credential not found"),
            Self::AuthenticationFailed => f.write_str("credential authentication failed"),
            Self::AlreadyExists { name } => write!(f, "credential '{name}' already exists"),
            Self::Malformed => f.write_str("credential blob is malformed"),
        }
    }
}

impl std::error::Error for CredentialError {}

/// Strategy for sourcing the 32-byte sealing key.
pub trait KeyProvider {
    /// Returns the next sealing key. Implementations are
    /// expected to return the *same* key for the lifetime
    /// of the store; rotation is handled by creating a
    /// new store and re-sealing.
    fn sealing_key(&self) -> [u8; 32];
}

/// A key provider that returns a fresh random key every
/// time it is asked. Suitable for tests; the resulting
/// store cannot be re-opened.
pub struct RandomKeyProvider;

impl KeyProvider for RandomKeyProvider {
    fn sealing_key(&self) -> [u8; 32] {
        let mut key = [0u8; 32];
        rand::thread_rng().fill_bytes(&mut key);
        key
    }
}

/// A key provider that returns a caller-supplied key. The
/// key is wiped on drop.
pub struct StaticKeyProvider([u8; 32]);

impl StaticKeyProvider {
    pub fn new(key: [u8; 32]) -> Self {
        Self(key)
    }
}

impl Drop for StaticKeyProvider {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

impl KeyProvider for StaticKeyProvider {
    fn sealing_key(&self) -> [u8; 32] {
        self.0
    }
}

/// The sealed credential store itself.
pub struct SealedStore<K: KeyProvider> {
    key_provider: K,
    entries: std::collections::HashMap<String, Credential>,
}

impl<K: KeyProvider> SealedStore<K> {
    /// Creates a new empty store backed by `key_provider`.
    pub fn new(key_provider: K) -> Self {
        Self { key_provider, entries: std::collections::HashMap::new() }
    }

    /// Returns the number of stored credentials.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Returns `true` if the store holds no credentials.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Returns a list of credential names. Order is not
    /// guaranteed; the store is a `HashMap` underneath.
    pub fn names(&self) -> Vec<String> {
        let mut out: Vec<String> = self.entries.keys().cloned().collect();
        out.sort();
        out
    }

    /// Returns `true` if a credential with `name` exists.
    pub fn contains(&self, name: &str) -> bool {
        self.entries.contains_key(name)
    }

    /// Returns the metadata (name + blob, never plaintext)
    /// for `name`, or `None` if not present.
    pub fn get(&self, name: &str) -> Option<&Credential> {
        self.entries.get(name)
    }

    /// Seals `plaintext` under `name` and inserts it. If
    /// `name` already exists, the call is rejected with
    /// `CredentialError::AlreadyExists`; the caller can
    /// opt into overwrite by passing `force = true`.
    ///
    /// `label` is optional metadata and is not
    /// authenticated.
    pub fn seal(
        &mut self,
        name: &str,
        plaintext: &str,
        label: Option<&str>,
        force: bool,
    ) -> Result<&Credential, CredentialError> {
        if !force && self.entries.contains_key(name) {
            return Err(CredentialError::AlreadyExists { name: name.to_string() });
        }
        let key_bytes = self.key_provider.sealing_key();
        // `Array::from` is the canonical conversion from
        // a fixed-size byte array to the hybrid-array
        // representation that aes-gcm uses for keys and
        // nonces. The `try_from`/`from_slice` pattern is
        // deprecated in aes-gcm 0.11.
        let key_array = Array::<u8, _>::from(key_bytes);
        let cipher = Aes256Gcm::new(&key_array);
        // The store never lets the key escape, but a
        // caller-supplied `StaticKeyProvider` does retain
        // the key inside its own buffer, so we still
        // zeroize the local copy after constructing the
        // cipher.
        let mut key_bytes = key_bytes;
        key_bytes.zeroize();
        let mut nonce_bytes = [0u8; 12];
        rand::thread_rng().fill_bytes(&mut nonce_bytes);
        let nonce_array: Array<u8, _> = Array::from(nonce_bytes);
        let ciphertext = cipher
            .encrypt(&nonce_array, plaintext.as_bytes())
            .map_err(|e| {
                eprintln!("[aether-security] seal encrypt failed: {e:?}");
                CredentialError::AuthenticationFailed
            })?;
        let mut bytes = Vec::with_capacity(12 + ciphertext.len());
        bytes.extend_from_slice(&nonce_bytes);
        bytes.extend_from_slice(&ciphertext);
        let sealed_at_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_millis().min(u128::from(u64::MAX)) as u64)
            .unwrap_or(0);
        let blob = SealedBlob {
            bytes,
            label: label.map(str::to_string),
            sealed_at_ms,
        };
        let credential =
            Credential { name: name.to_string(), blob, plaintext_len: plaintext.len() };
        self.entries.insert(name.to_string(), credential);
        Ok(self.entries.get(name).expect("insert succeeded"))
    }

    /// Decrypts and returns the plaintext for `name`. The
    /// returned `Secret<String>` is wiped on drop.
    pub fn unseal(&self, name: &str) -> Result<Secret<String>, CredentialError> {
        let credential =
            self.entries.get(name).ok_or(CredentialError::NotFound)?;
        let bytes = &credential.blob.bytes;
        // The wire format is `nonce(12) || ciphertext_with_tag(N+16)`,
        // so the minimum length is 12 (nonce) + 16 (empty-ciphertext tag) = 28.
        if bytes.len() < 12 + 16 {
            return Err(CredentialError::Malformed);
        }
        let (nonce_bytes, ciphertext_with_tag) = bytes.split_at(12);
        let key_bytes = self.key_provider.sealing_key();
        let key_array = Array::<u8, _>::from(key_bytes);
        let cipher = Aes256Gcm::new(&key_array);
        let mut key_bytes = key_bytes;
        key_bytes.zeroize();
        // The nonce region was sliced from the wire-format
        // bytes, so it is exactly 12 bytes long by
        // construction. `Array::from` accepts a fixed-size
        // byte array; the `split_at(12)` on the length-
        // checked input guarantees the type matches.
        let nonce_array: Array<u8, _> = match nonce_bytes.try_into() {
            Ok(arr) => arr,
            Err(_) => return Err(CredentialError::Malformed),
        };
        let plaintext = cipher
            .decrypt(&nonce_array, ciphertext_with_tag)
            .map_err(|_| CredentialError::AuthenticationFailed)?;
        let s = std::str::from_utf8(&plaintext).map_err(|_| CredentialError::Malformed)?;
        Ok(Secret::new(s.to_string()))
    }

    /// Removes `name` from the store. Returns the removed
    /// credential so the caller can decide what to do
    /// with it; the removed `SealedBlob` is plaintext-free.
    pub fn remove(&mut self, name: &str) -> Result<Credential, CredentialError> {
        self.entries.remove(name).ok_or(CredentialError::NotFound)
    }

    /// Drops every credential from the store. Does not
    /// affect the key provider.
    pub fn clear(&mut self) {
        self.entries.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn store() -> SealedStore<StaticKeyProvider> {
        let key = [0x42u8; 32];
        SealedStore::new(StaticKeyProvider::new(key))
    }

    #[test]
    fn seal_then_unseal_round_trip() {
        let mut s = store();
        s.seal("api_key", "super-secret-value", Some("prod"), false).unwrap();
        let recovered = s.unseal("api_key").unwrap();
        assert_eq!(recovered.expose(), "super-secret-value");
    }

    #[test]
    fn seal_rejects_duplicate_without_force() {
        let mut s = store();
        s.seal("api_key", "v1", None, false).unwrap();
        let err = s.seal("api_key", "v2", None, false).unwrap_err();
        assert_eq!(err, CredentialError::AlreadyExists { name: "api_key".to_string() });
    }

    #[test]
    fn seal_with_force_overwrites() {
        let mut s = store();
        s.seal("api_key", "v1", None, false).unwrap();
        s.seal("api_key", "v2", None, true).unwrap();
        let recovered = s.unseal("api_key").unwrap();
        assert_eq!(recovered.expose(), "v2");
    }

    #[test]
    fn unseal_with_wrong_key_fails() {
        let mut s1 = SealedStore::new(StaticKeyProvider::new([0x42u8; 32]));
        s1.seal("api_key", "value", None, false).unwrap();
        // Copy the sealed blob into a new store with a
        // different key.
        let credential = s1.get("api_key").unwrap().clone();
        let mut s2 = SealedStore::new(StaticKeyProvider::new([0x99u8; 32]));
        s2.entries.insert("api_key".to_string(), credential);
        let err = s2.unseal("api_key").unwrap_err();
        assert_eq!(err, CredentialError::AuthenticationFailed);
    }

    #[test]
    fn tampered_ciphertext_is_rejected() {
        let mut s = store();
        s.seal("api_key", "value", None, false).unwrap();
        let credential = s.get("api_key").unwrap().clone();
        // Flip a bit inside the ciphertext region. The
        // tag covers the entire payload, so any single
        // bit flip is enough to fail authentication.
        let mut bad = credential;
        let idx = 12 + 2;
        bad.blob.bytes[idx] ^= 0x01;
        s.entries.insert("api_key".to_string(), bad);
        let err = s.unseal("api_key").unwrap_err();
        assert_eq!(err, CredentialError::AuthenticationFailed);
    }

    #[test]
    fn tampered_tag_is_rejected() {
        let mut s = store();
        s.seal("api_key", "value", None, false).unwrap();
        let credential = s.get("api_key").unwrap().clone();
        let mut bad = credential;
        // Flip a bit in the last 16 bytes (which is the
        // GCM tag, appended to the ciphertext by aes-gcm).
        let last = bad.blob.bytes.len() - 1;
        bad.blob.bytes[last] ^= 0x01;
        s.entries.insert("api_key".to_string(), bad);
        let err = s.unseal("api_key").unwrap_err();
        assert_eq!(err, CredentialError::AuthenticationFailed);
    }

    #[test]
    fn malformed_blob_is_rejected() {
        let mut s = store();
        s.seal("api_key", "value", None, false).unwrap();
        let credential = s.get("api_key").unwrap().clone();
        let mut bad = credential;
        // Truncate to less than nonce + tag length.
        bad.blob.bytes.truncate(10);
        s.entries.insert("api_key".to_string(), bad);
        let err = s.unseal("api_key").unwrap_err();
        assert_eq!(err, CredentialError::Malformed);
    }

    #[test]
    fn remove_returns_the_blob() {
        let mut s = store();
        s.seal("api_key", "value", None, false).unwrap();
        let removed = s.remove("api_key").unwrap();
        assert_eq!(removed.name, "api_key");
        assert!(!s.contains("api_key"));
    }

    #[test]
    fn remove_unknown_name_errors() {
        let mut s = store();
        let err = s.remove("nope").unwrap_err();
        assert_eq!(err, CredentialError::NotFound);
    }

    #[test]
    fn names_lists_every_credential_sorted() {
        let mut s = store();
        s.seal("zeta", "z", None, false).unwrap();
        s.seal("alpha", "a", None, false).unwrap();
        s.seal("mu", "m", None, false).unwrap();
        assert_eq!(s.names(), vec!["alpha".to_string(), "mu".to_string(), "zeta".to_string()]);
    }

    #[test]
    fn clear_drops_every_credential() {
        let mut s = store();
        s.seal("a", "1", None, false).unwrap();
        s.seal("b", "2", None, false).unwrap();
        s.clear();
        assert!(s.is_empty());
        assert_eq!(s.len(), 0);
    }

    #[test]
    fn plaintext_is_not_present_in_sealed_blob() {
        // Belt-and-braces: the sealed blob's bytes must
        // not contain the plaintext. AES-GCM is a stream
        // cipher, but the chance of a literal substring
        // match for a credential of any reasonable length
        // is negligible; for very short credentials the
        // test still holds because the nonce is random.
        let mut s = store();
        s.seal("api_key", "super-secret-value", None, false).unwrap();
        let blob = &s.get("api_key").unwrap().blob.bytes;
        let blob_str = String::from_utf8_lossy(blob);
        assert!(!blob_str.contains("super-secret-value"));
    }

    #[test]
    fn two_seals_of_the_same_value_produce_different_blobs() {
        // The nonce is fresh per call, so two seals of
        // the same plaintext with the same key produce
        // different ciphertexts. This is required for
        // semantic security under a static key.
        let mut s = store();
        s.seal("a", "value", None, false).unwrap();
        s.seal("b", "value", None, false).unwrap();
        let a = s.get("a").unwrap().blob.bytes.clone();
        let b = s.get("b").unwrap().blob.bytes.clone();
        assert_ne!(a, b);
    }

    #[test]
    fn random_key_provider_cannot_round_trip() {
        // The point of `RandomKeyProvider` is to produce a
        // fresh key on every call. A store backed by it
        // can seal, but the very next `sealing_key()` call
        // will return a different key, so `unseal` must
        // fail with `AuthenticationFailed`. This is by
        // design — `RandomKeyProvider` exists for tests
        // and benchmarks that need a valid key but do not
        // need to unseal.
        let mut s = SealedStore::new(RandomKeyProvider);
        s.seal("k", "v", None, false).unwrap();
        let err = s.unseal("k").unwrap_err();
        assert_eq!(err, CredentialError::AuthenticationFailed);
    }

    #[test]
    fn static_key_provider_round_trip() {
        // The companion of the random-provider test:
        // a static key must round-trip, and the test uses
        // it as a sanity check that `RandomKeyProvider`
        // really is the cause of the failure above.
        let mut s = SealedStore::new(StaticKeyProvider::new([0xAAu8; 32]));
        s.seal("k", "v", None, false).unwrap();
        let recovered = s.unseal("k").unwrap();
        assert_eq!(recovered.expose(), "v");
    }

    #[test]
    fn secret_into_inner_returns_the_string() {
        let s: Secret<String> = Secret::new("hello".to_string());
        let inner = s.into_inner();
        assert_eq!(inner, "hello");
    }

    #[test]
    fn credential_error_display_messages_are_distinct() {
        // The error variants each carry a distinct
        // message so a logged failure is enough to
        // diagnose the problem.
        assert_eq!(CredentialError::NotFound.to_string(), "credential not found");
        assert_eq!(
            CredentialError::AuthenticationFailed.to_string(),
            "credential authentication failed"
        );
        assert_eq!(
            CredentialError::AlreadyExists { name: "x".to_string() }.to_string(),
            "credential 'x' already exists"
        );
        assert_eq!(CredentialError::Malformed.to_string(), "credential blob is malformed");
    }
}
